@startuml
class UMLGeneratorApp {
+ {static} main(args: String[]): void
}

class GraphGenerator {
- recursive: boolean
- access: AccessLevel
+ execute(classNames: List<String>): Graph
}

enum AccessLevel {
+ PUBLIC
+ PRIVATE
+ PROTECTED
}

class ClassCell {
- classNode: ClassNode
- edges: List<Edge>
- renderAccess: AccessLevel
+ getName(): String
+ getPrettyName(): String
+ getAccess(): int
+ getFields(): List<FieldNode>
+ getMethods(): List<MethodNode>
+ getImplements(): List<ClassNode>
+ getSuper(): ClassNode
+ equals(other: Object): boolean
+ hasNode(otherNode: ClassNode): boolean
+ addEdge(e: Edge): void
+ getAllRelatives(): List<String>
}

class Edge {
- originClass: ClassCell
- destClass: ClassCell
- relation: Relation
+ getOrigin(): ClassCell
+ getDestination(): ClassCell
+ getRelation(): Relation
}

class Parser {
- patterns: Map<Integer, Pattern>
+ parseGraph(graph: Graph): List<GraphvizElement>
+ addPattern(pattern: Pattern, priority: Integer): boolean
+ remPattern(pattern: Pattern): boolean
}
note top of Parser
  The addPattern() method checks to ensure
  there are no repeated priorities and no
  repeated patterns. Patterns will be searched
  for from lowest priority value to highest.
end note

class Graph {
- cells: List<ClassCell>
- edges: List<Edge>
+ addClass(cell: ClassCell): boolean
+ getCells(): List<ClassCell>
+ addEdge(edge: Edge): boolean
+ getEdges(): List<Edge>
+ copy(): Graph
+ containsNode(node: ClassNode): ClassCell
}

abstract class Pattern {
- translateFieldNode(node: FieldNode): String
- translateMethodNode(node: MethodNode): String
- getAccessChar(access: int): char
+ toGraphviz(): List<GraphvizElement>
+ {abstract} detect(graphToSearch: Graph): Graph
}

abstract class PatternDecorator extends Pattern {
+ toGraphviz(): List<GraphvizElement>
+ detect(graphToSearch: Graph): Graph
}

class ColoredDecorator extends PatternDecorator {
+ toGraphviz(): List<GraphvizElement>
}

class ArrowDecorator extends PatternDecorator {
+ toGraphviz(): List<GraphvizElement>
}

class SingletonPattern extends Pattern {
+ detect(graphToSearch: Graph): Graph
}

class AdapterPattern extends Pattern {
+ detect(graphToSearch: Graph): Graph
}

class DecoratorPattern extends Pattern {
+ toGraphviz(): List<GraphvizElement>
+ detect(graphToSearch: Graph): Graph
}

class IdentityPattern extends Pattern {
+ detect(graphToSearch: Graph): Graph
}

enum Relation {
+ INHERITS
+ IMPLEMENTS
+ CONTAINS
}

abstract class GraphvizElement {
- attributes: Map<String, String>
+ addAttr(var: String, val: String): void
+ remAttr(var: String): void
+ getAttr(var: String): String
+ {abstract} toGraphviz(): String
+ {abstract} getIdentifier(): String
}
note top of GraphvizElement
  The map is from a Graphviz attribute to its value.
  getIdentifier() must return a String unique to this
  GraphvizElement but shared with other GraphvizElement\'s
  that should overwrite this one.
end note

class GraphvizNode extends GraphvizElement {
- name: String
+ toGraphviz(): String
+ getIdentifier(): String
}

class GraphvizEdge extends GraphvizElement {
- fromNode: String
- toNode: String
+ toGraphviz(): String
+ getIdentifier(): String
}

class GraphvizGlobalParam extends GraphvizElement {
+ toGraphviz(): String
+ getIdentifier(): String
}

interface Exporter {
+ export(graphviz: List<GraphvizElement>): void
}

class FileExporter implements Exporter {
+ export(graphviz: List<GraphvizElement>): void
}

UMLGeneratorApp --> GraphGenerator
UMLGeneratorApp --> Parser
UMLGeneratorApp --> Exporter
GraphGenerator --> Graph
GraphGenerator --> AccessLevel
ClassCell --> Edge
ClassCell --> AccessLevel
Edge --> ClassCell
Edge --> Relation
Parser --> Pattern
Pattern --> Graph
PatternDecorator --> Pattern
Pattern --> GraphvizElement
Graph --> ClassCell
Graph --> Edge
Parser --> Graph
Parser --> GraphvizElement
Exporter --> GraphvizElement
@enduml
